src/Entity/Fichier.php
<?php

namespace App\Entity;

use App\Repository\FichierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FichierRepository::class)
 */
class Fichier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=150)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $extension;

    /**
     * @ORM\Column(type="float")
     */
    private $taille;

    /**
     * @ORM\ManyToOne(targetEntity=Utilisateur::class, inversedBy="fichiers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Utilisateur;

    /**
     * @ORM\ManyToMany(targetEntity=Theme::class, inversedBy="fichiers")
     */
    private $themes;

    /**
     * @ORM\OneToMany(targetEntity=Telechargement::class, mappedBy="fichier")
     */
    private $telechargements;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vraiNom;

    public function __construct()
    {
        $this->themes = new ArrayCollection();
        $this->telechargements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom()
    {
        return $this->nom;
    }

    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getExtension(): ?string
    {
        return $this->extension;
    }

    public function setExtension(string $extension): self
    {
        $this->extension = $extension;

        return $this;
    }

    public function getTaille(): ?float
    {
        return $this->taille;
    }

    public function setTaille(float $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    /**
     * @return Collection|Theme[]
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function addTheme(Theme $theme): self
    {
        if (!$this->themes->contains($theme)) {
            $this->themes[] = $theme;
        }

        return $this;
    }

    public function removeTheme(Theme $theme): self
    {
        if ($this->themes->contains($theme)) {
            $this->themes->removeElement($theme);
        }

        return $this;
    }

    /**
     * @return Collection|Telechargement[]
     */
    public function getTelechargements(): Collection
    {
        return $this->telechargements;
    }

    public function addTelechargement(Telechargement $telechargement): self
    {
        if (!$this->telechargements->contains($telechargement)) {
            $this->telechargements[] = $telechargement;
            $telechargement->setFichier($this);
        }

        return $this;
    }

    public function removeTelechargement(Telechargement $telechargement): self
    {
        if ($this->telechargements->contains($telechargement)) {
            $this->telechargements->removeElement($telechargement);
            // set the owning side to null (unless already changed)
            if ($telechargement->getFichier() === $this) {
                $telechargement->setFichier(null);
            }
        }

        return $this;
    }

    public function getVraiNom(): ?string
    {
        return $this->vraiNom;
    }

    public function setVraiNom(string $vraiNom): self
    {
        $this->vraiNom = $vraiNom;

        return $this;
    }
}

templates/fichier/ajout_fichier.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}
    {{parent()}}
     Ajouter Fichier
{% endblock %}
 
{% block body %}
    {{parent()}}
    <div class="container">
        <div class="row justify-content-center">
            <h1 class="text-center text-primary p-4">Ajouter un fichier
            </h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-12 bg-white p-4 m-0 text-primary">
                {{ form_start(form) }}
                <div class="form-group">
                    {{ form_label(form.nom, 'Nom ', {'label_attr': {'class': 'font-weight-bold'}}) }}
                    {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                </div>
     
        </div>
    </div>
 
    {{form_end(form) }}
 
 
{% endblock %}
    

templates/fichier/liste_fichiers.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{parent()}}
	Liste Fichiers
{% endblock %}

{% block body %}
	{{parent()}}
	<div class="container">
		<div class="row justify-content-center">
			<h1 class="text-center text-primary p-4">Liste Fichiers</h1>
		</div>

		<div class="row justify-content-center">
			<table class="table table-hover">
				<thead>
					<tr class="table-dark">

						
						
						<td>VraiNom</td>
						<td>Taille</td>
						<td>Extension</td>
                        <td>Propriétaire</td>

					</tr>
          </thead>
          <tbody>


					{% for fichier in fichiers %}
						<tr class="{{ cycle(['table-primary', 'table-secondary'],loop.index0)}}">
                        <td><a href="{{path('telechargement_fichier',{'id':fichier.id})}}">{{fichier.vraiNom}}</a> </td>
						{% set tfichier = fichier.taille %}
						{% set mesure = "O" %}
						{% if tfichier > 1000 %}
						{% set tfichier = tfichier/1000 %}
						{% set mesure = "Ko" %}
						{% if tfichier > 1000 %}
						{% set tfichier = tfichier/1000 %}
						{% set mesure = "Mo" %}
						{% if tfichier > 1000 %}
						{% set tfichier = tfichier/1000 %}
						{% set mesure = "Go" %}
						{% endif %}
						{% endif %}
						{% endif %}

                        <td> {{tfichier}} {{mesure}} </td>
                        <td> {{fichier.extension}} </td>
                        <td> {{fichier.utilisateur.prenom}}
                         {{fichier.utilisateur.nom}} </td>
						 <td><a href="{{path('liste_fichiers',{'supp':fichier.id})}}" class="text-white"><span class="material-icons" title="Supprimer le fichier">delete</span></a></td>

						</tr>
					{% endfor %}

				</tbody>
			</table>


		</div>
	{% endblock %}